name: Run Agify tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ vars.BASE_URL }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tool versions
        uses: jdx/mise-action@v2

      - name: Install Node dependencies
        run: pnpm install

      - name: Run Playwright BDD tests
        run: pnpm pw-smoke
        continue-on-error: true

      - name: Run Cucumber tests
        run: pnpm cu-smoke
        continue-on-error: true

      - name: Auth to GCloud
        if: always()
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.SERVICE_ACCOUNT }}

      - name: Upload Playwright Report
        if: always() && hashFiles('playwright-report/**/*') != ''
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: playwright-report/
          destination: sqa-tech-task-test-reports/${{ github.run_id }}/playwright/
          process_gcloudignore: false

      - name: Upload Cucumber Report
        if: always() && hashFiles('cucumber-report/**/*') != ''
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: cucumber-report/
          destination: sqa-tech-task-test-reports/${{ github.run_id }}/cucumber/
          process_gcloudignore: false

      - name: Add links to step summary
        if: always() && (hashFiles('playwright-report/**/*') != '' || hashFiles('cucumber-report/**/*') != '')
        run: |
          PLAYWRIGHT_URL="https://storage.googleapis.com/sqa-tech-task-test-reports/${{ github.run_id }}/playwright/index.html"
          CUCUMBER_URL="https://storage.googleapis.com/sqa-tech-task-test-reports/${{ github.run_id }}/cucumber/index.html"
          echo "🎭 [View Playwright Report](${PLAYWRIGHT_URL})" >> $GITHUB_STEP_SUMMARY
          echo "🥒 [View Cucumber Report](${CUCUMBER_URL})" >> $GITHUB_STEP_SUMMARY
