name: Run Agify tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ vars.BASE_URL }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tool versions
        uses: jdx/mise-action@v2

      - name: Install Node dependencies
        run: pnpm install

      - name: Run Playwright BDD tests
        run: pnpm pw-smoke

      - name: Run Cucumber tests
        run: pnpm cu-smoke

      - name: Auth to GCloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.SERVICE_ACCOUNT }}

      - name: Upload Playwright Report
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: playwright-report/
          destination: gs://sqa-tech-task/${{ github.run_id }}/playwright/

      - name: Upload Cucumber Report
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: cucumber-report/
          destination: gs://sqa-tech-task/${{ github.run_id }}/cucumber/

      - name: Add links to step summary
        run: |
          PLAYWRIGHT_URL="https://storage.googleapis.com/sqa-tech-task/${{ github.run_id }}/playwright/index.html"
          CUCUMBER_URL="https://storage.googleapis.com/sqa-tech-task/${{ github.run_id }}/cucumber/index.html"
          echo "🎭 [View Playwright Report](${PLAYWRIGHT_URL})" >> $GITHUB_STEP_SUMMARY
          echo "🥒 [View Cucumber Report](${CUCUMBER_URL})" >> $GITHUB_STEP_SUMMARY
